---
title: "1. Sequencing Depth"
author: "Avril Metcalfe-Roach"
date: "2026-05-15"
output: html_document
---

```{r}
library(tidyverse)
library(phyloseq)
library(vegan)

ps = readRDS('../Data/pilot_phyloseq.rds')
meta = data.frame(ps@sam_data)
```

```{r}
psrare_s = ps %>% subset_samples(Type=='Saliva') %>% rarefy_even_depth(rngseed = 421)
psrare_g = ps %>% subset_samples(Type=='Subgingival') %>% rarefy_even_depth(rngseed = 421)
```

# 1. Taxa bar plot

```{r}
ps_family = tax_glom(ps,'Family')

relab = ps_family %>% 
  microbiome::transform('compositional') %>% 
  psmelt()

# average abundances of each family
sum_of_each_family = taxa_sums(ps_family)
avg_of_each_family = sum_of_each_family/sum(sum_of_each_family)

# Find which ones are <1%
below_1 = avg_of_each_family[avg_of_each_family<0.01]
to_change = names(below_1) 

relab_modified = relab
unique(relab_modified$Family)
relab_modified$Family[relab_modified$OTU %in% to_change] = '<1%'
unique(relab_modified$Family)

# plot it!

plot_abfilt = relab_modified %>% 
  ggplot(aes(Sample,Abundance,fill=Family)) +
  geom_col(position='stack') +
  facet_wrap(~Type+Number, ncol = 3, scales = 'free') +
  theme_classic(base_size=18) +
  theme(axis.text.x = element_blank()) +
  xlab(NULL)

plot_abfilt # Perfect!
```

# Alpha Diversity

```{r Saliva}
set.seed(421)
p = plot_richness(psrare_s, x = 'Kit', 
                  measures = c('Observed','Shannon','Simpson'),
                  color = 'Kit',
                  )

# Pull the data from the plot:
pdata = p$data

# Plot
plot_s = pdata %>% ggplot(aes(Kit,value,col = Kit)) +
  geom_point()+
  # add a line to its matching sample across both Kit values
  geom_line(aes(group=Number),col='black') +
  theme_classic(base_size=18) +
  facet_wrap(~variable,ncol=3,scales = 'free_y') +
  ylab('Alpha Diversity') + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45,vjust=1,hjust=1)) +
  ylim(0, NA)

# stats
stats_s = pdata %>% 
  group_by(variable) %>% 
  summarise(t_stat = t.test(value[Kit=='DBT'], value[Kit=='PF'], paired=T)$statistic,
            p_value = t.test(value[Kit=='DBT'], value[Kit=='PF'], paired=T)$p.value) %>%
  ungroup() %>% 
  mutate(Type = 'Saliva',.before='variable')
```

```{r Subgingival}
set.seed(421)
p = plot_richness(psrare_g, x = 'Kit', 
                  measures = c('Observed','Shannon','Simpson'),
                  color = 'Kit',
                  )

# Pull the data from the plot:
pdata = p$data

# Plot
plot_g = pdata %>% ggplot(aes(Kit,value,col = Kit)) +
  geom_point()+
  # add a line to its matching sample across both Kit values
  geom_line(aes(group=Number),col='black') +
  theme_classic(base_size=18) +
  facet_wrap(~variable,ncol=3,scales = 'free_y') +
  ylab('Alpha Diversity') + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45,vjust=1,hjust=1)) +
  ylim(0, NA)

# stats
stats_g = pdata %>% 
  group_by(variable) %>% 
  summarise(t_stat = t.test(value[Kit=='DBT'], value[Kit=='PF'], paired=T)$statistic,
            p_value = t.test(value[Kit=='DBT'], value[Kit=='PF'], paired=T)$p.value) %>%
  ungroup() %>% 
  mutate(Type = 'Subgingival',.before='variable')
```

```{r}
plot_s; plot_g
stats_s; stats_g
```

# Beta Diversity

```{r}
ps_bray_s = phyloseq::distance(psrare_s, method = "bray")
ps_bray_g = phyloseq::distance(psrare_g, method = "bray")
```

```{r Saliva}
# MDS scaling
set.seed(421)
mds = metaMDS(ps_bray_s)

# Extract data
mds_data = mds$points %>% as.data.frame %>%
  merge(sample_data(psrare_s), by='row.names', sort=F)
head(mds_data)

# Plot it
p = mds_data %>%
  mutate(Number= factor(.$Number)) %>%
  ggplot(aes(MDS1,MDS2,color = Kit, shape=Number)) +
  geom_point(size=3) +
  stat_ellipse() +
  theme_classic(base_size=18)
p

# stats
metadata = sample_data(psrare_s) %>% data.frame()
adonis2(ps_bray_s ~ Kit, data = metadata)
```

```{r Subgingival}
# MDS scaling
set.seed(421)
mds = metaMDS(ps_bray_g)

# Extract data
mds_data = mds$points %>% as.data.frame %>%
  merge(sample_data(psrare_g), by='row.names', sort=F)
head(mds_data)

# Plot it
p = mds_data %>%
  mutate(Number= factor(.$Number)) %>%
  ggplot(aes(MDS1,MDS2,color = Kit, shape=Number)) +
  geom_point(size=3) +
  stat_ellipse() +
  theme_classic(base_size=18)
p

# stats
metadata = sample_data(psrare_g) %>% data.frame()
adonis2(ps_bray_g ~ Kit, data = metadata)
```

